# yaml-language-server: $schema=https://raw.githubusercontent.com/docker/compose/refs/heads/v1/compose/config/compose_spec.json

services:
  redis:
    image: redis:8.6.0
    ports:
      - 6379:6379
    restart: always

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  proxy:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always
