# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  deploy:
    taskfile: ./deploy/Taskfile.yml
    dir: ./deploy/
  docker:
    taskfile: ./Taskfile.docker.yml
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend/
  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web/

tasks:
  push-all:
    desc: Build and push all images
    deps: [backend:push, web:push]

  setup:
    cmds:
      - task: deploy:start-kind-with-registry
      - task: deploy:tofu:apply-all
      - task: push-all

  teardown:
    cmds:
      - task: deploy:tofu:destroy-all
      - task: deploy:stop-kind-with-registry
