# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

includes:
  deploy:tofu:
    taskfile: ./deploy/tofu/Taskfile.yml
    dir: ./deploy/tofu/
  docker:
    taskfile: ./Taskfile.docker.yml
  backend:
    taskfile: ./backend/Taskfile.yml
    dir: ./backend/
  web:
    taskfile: ./web/Taskfile.yml
    dir: ./web/

tasks:
  push-all:
    desc: Build and push all images
    deps: [backend:push, web:push]
