apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: kind-registry:5000/web
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
