apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - env:
            - name: REDIS_HOST
              value: redis.webchat.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          image: localhost:5001/backend:0.1.1
          name: backend
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
