# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  apply-infra:
    dir: infra
    cmds:
      - pwd
      - tofu apply -auto-approve -var-file="../common.tfvars"

  get-argo-password:
    cmds:
      - kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
    silent: true
